apiVersion: v1
data:
  default.conf: |-
    # External provided default config
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /test {
            alias /usr/share/nginx/html/test.html;
            default_type text/html;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
  namespace: dev-personal-namespace
